"""
Quick Start Guide - Ask Lenny RAG System
"""

def print_instructions():
    print("=" * 70)
    print("🎙️ ASK LENNY - Quick Start Guide")
    print("=" * 70)
    print()
    
    print("📋 SETUP STEPS:")
    print()
    
    print("1️⃣  Install Dependencies")
    print("   Option A (Recommended): Use setup script")
    print("      bash setup.sh")
    print()
    print("   Option B: Manual setup")
    print("      python3 -m venv venv")
    print("      source venv/bin/activate")
    print("      pip install -r requirements.txt")
    print()
    
    print("2️⃣  Configure API Keys")
    print("   Create a .env file:")
    print("      cp env-template.txt .env")
    print()
    print("   Edit .env and add your keys:")
    print("      OPENAI_API_KEY=sk-...")
    print("      ANTHROPIC_API_KEY=sk-ant-...")
    print()
    print("   Get API keys from:")
    print("      • OpenAI: https://platform.openai.com/api-keys")
    print("      • Anthropic: https://console.anthropic.com/")
    print()
    
    print("3️⃣  Ingest Transcripts (One-time, ~5-10 minutes)")
    print("      python ingest_transcripts.py")
    print()
    print("   This will:")
    print("      • Load 269 transcript files")
    print("      • Chunk them into ~1000 token pieces")
    print("      • Create embeddings using OpenAI")
    print("      • Store in ChromaDB (local vector database)")
    print()
    
    print("4️⃣  Start Querying!")
    print("   Option A: Web Interface (Recommended)")
    print("      streamlit run app.py")
    print()
    print("   Option B: Python API")
    print("      python rag_system.py")
    print()
    print("   Option C: Use in code")
    print("      from rag_system import LennyRAG")
    print("      rag = LennyRAG()")
    print("      result = rag.ask('Your question here')")
    print()
    
    print("=" * 70)
    print("💡 EXAMPLE QUERIES:")
    print("=" * 70)
    print()
    print("• What causes analytics projects to fail?")
    print("• How long does it take to build trust in data systems?")
    print("• What do founders say about build vs buy decisions?")
    print("• Schema evolution challenges in analytics")
    print("• Data governance at scale")
    print("• Why did companies switch from Mixpanel?")
    print("• What makes Palantir's data platform different?")
    print()
    
    print("=" * 70)
    print("📁 PROJECT STRUCTURE:")
    print("=" * 70)
    print()
    print("ask-lenny/")
    print("├── app.py                 # Streamlit web interface")
    print("├── rag_system.py          # Core RAG implementation")
    print("├── ingest_transcripts.py  # One-time setup")
    print("├── requirements.txt       # Python dependencies")
    print("├── setup.sh              # Automated setup")
    print("├── .env                  # API keys (you create this)")
    print("└── data/")
    print("    └── vector_db/        # ChromaDB storage (auto-created)")
    print()
    
    print("=" * 70)
    print("🐛 TROUBLESHOOTING:")
    print("=" * 70)
    print()
    print("❌ 'Collection not found' error")
    print("   → Run: python ingest_transcripts.py")
    print()
    print("❌ 'OPENAI_API_KEY not found' error")
    print("   → Create .env file with your API keys")
    print()
    print("❌ 'Transcripts not found' error")
    print("   → Make sure folder structure is correct:")
    print("      Enterprise SaaS insights/")
    print("      ├── ask-lenny/")
    print("      └── lennys-podcast-transcripts/")
    print()
    print("❌ Embeddings are slow/expensive")
    print("   → First ingestion costs ~$2-3 (one-time)")
    print("   → Queries cost ~$0.001 each")
    print("   → Total: <$5 for full setup + 100 queries")
    print()
    
    print("=" * 70)
    print("💰 COST ESTIMATES:")
    print("=" * 70)
    print()
    print("One-time Setup (Ingestion):")
    print("  • ~3000 chunks × 1500 tokens = 4.5M tokens")
    print("  • OpenAI embeddings: ~$0.50")
    print("  • Total: ~$0.50")
    print()
    print("Per Query:")
    print("  • 10 chunks × 1000 tokens = 10k input tokens")
    print("  • Claude Sonnet 4: ~$0.03 per query")
    print("  • 100 queries: ~$3")
    print()
    print("Total for full setup + 100 queries: ~$3.50")
    print()
    
    print("=" * 70)
    print("🚀 READY TO START?")
    print("=" * 70)
    print()
    print("Run:  bash setup.sh")
    print()

if __name__ == "__main__":
    print_instructions()
